spring: 
    profiles: 
        active:
           - dev
---
server: 
    port: 8101
spring:
    profiles: dev
    application:
        name: springcloud-config-client-dev
eureka:
    client: 
        service-url: 
            defaultZone: http://eureka-dev.com:7001/eureka/
---
server: 
    port: 8102
spring:
    profiles: test
    application:
        name: springcloud-config-client-test
eureka:
    client: 
        service-url: 
            defaultZone: http://eureka-test.com:7001/eureka/